
const BACKGROUND_COLOR="white";

const BACKGROUND_COLOR_WIDGET="#D9D9D9";

const MAIN_COLOR="#ADB2D3";

const COLOR_TEXT_BUTTON="black";

const SIZE_TITLE=40;

const SIZE_MEDIUM=20;

const SHADOW_COLOR="#171717";

export { BACKGROUND_COLOR, BACKGROUND_COLOR_WIDGET, MAIN_COLOR, COLOR_TEXT_BUTTON, SIZE_TITLE, SIZE_MEDIUM, SHADOW_COLOR };