# Generated by Django 4.2.5 on 2023-10-22 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendNew', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResetPassword',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('token', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'resetPassword',
            },
        ),
        migrations.CreateModel(
            name='RuleModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, null=True)),
                ('description', models.CharField(max_length=255, null=True)),
                ('user_id', models.IntegerField()),
                ('trigger_id', models.IntegerField()),
                ('triggerToken', models.CharField(max_length=255, null=True)),
                ('action_id', models.IntegerField()),
                ('actionToken', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'rules',
            },
        ),
        migrations.CreateModel(
            name='ServiceModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('action', models.CharField(max_length=80)),
                ('type', models.CharField(max_length=80)),
            ],
            options={
                'db_table': 'service',
            },
        ),
        migrations.CreateModel(
            name='TokensModel',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('googleToken', models.CharField(max_length=255, null=True)),
                ('twitterToken', models.CharField(max_length=255, null=True)),
                ('githubToken', models.CharField(max_length=255, null=True)),
                ('discordToken', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'tokens',
            },
        ),
    ]
