# Generated by Django 4.2.5 on 2023-10-29 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendNew', '0002_resetpassword_rulemodel_servicemodel_tokensmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokensmodel',
            name='spotifyToken',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
